apiVersion: apps/v1
kind: Deployment
metadata: 
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
        containers:
            - name: server
              image: edsoncarlos33/server_fsfc
              ports: 
                - containerPort: 3000
